### ISSUE TITLE
Round trips: Rmd --> Google Doc --> Rmd

### ISSUE THREAD

**Issue by jennybc** [ropenscilabs/googlestuff#2]
Of course this would be fantastic. For the moment, however, we are focusing on the one way trip: Rmd :arrow_right: Google Doc. It is not clear how to un-knit a document and is not specific to Google Docs.

A few links I'm collecting relevant to round tripping and authoring Google Docs natively (vs via Word docx conversion on Google Drive):
- [Converting document formats with Pandoc](http://blogorama.nerdworks.in/converting-document-formats-with-pandoc/). Iintermediate JSON based abstract syntax tree (AST) representation of the document. Manipulating the AST.
- [Structure of a document](https://developers.google.com/apps-script/guides/docs#structure_of_a_document). "A Google Doc is structured much like an HTML document".
- [gdoc Structure Viewer](http://www.lorut.no/apps/gdoc-structure-viewer/), [gdoc2json](https://github.com/krilor/gdoc2json) on GitHub (via @dani-lbnl).

**Comment by noamross** [comment]
Relevant (from the original unconf issue): two-way knitting of .Rhtml: https://www.stat.auckland.ac.nz/~paul/Reports/invert/invert.html

**Comment by maelle** [comment]
This package was an experiment at an unconf and its development has stopped. The repo will become read-only.
