### ISSUE TITLE
Open the gdoc in the browser

### ISSUE THREAD

**Issue by jennybc** [ropenscilabs/googlestuff#5]
Create a function that makes this easier in the `rmarkdown::render()` case, i.e. something better than copying the link left as a message in the R Markdown log pane.

**Comment by noamross** [comment]
Perhaps the default behavior should be

```
if (interactive() & browse) browseURL(editURL)
```

With `browse=TRUE` the default?  Should browse be TRUE/FALSE/"force"?

**Comment by noamross** [comment]
I went with a browse=TRUE/FALSE option, with the default (NULL) opening the file if `interactive()` was true.  Closed by 0adcfae4.
